server:
 port: 8091
 error:
  include-binding-errors: always
  include-message: always
  include-stacktrace: never

spring:
 datasource:
    url: jdbc:mysql://localhost:3306/realestate_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

 jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL8Dialect
   properties:
      '[hibernate.format_sql]': true

info:
 application:
  name: 'Realestate Backend App'
  description: 'This is Realestate Backend  Project'
  version: '@project.version@'
